#!/usr/bin/env python3
"""Preflight check for a country assignment (Skill sections 5-9, 13, 40).

A fresh student workspace (e.g. a new Codex sandbox) can contain the repo
code and the country instructions without containing the *data* that
those instructions assume is already there: `data/reference_index.duckdb`,
`data/master/pollitik_master.xlsx`, or any local staging history. In that
state, nothing stops the student workflow from starting web research and
staging candidates with no real duplicate/reference check behind it -
`python/reference_lookup.py` silently reports `found_index: false` and
zero rows when the index is missing, which looks identical to "checked,
no duplicates found" if you don't know to look for it.

This script is a read-only, no-side-effect gate that runs BEFORE research
starts. It never fetches the web, never stages or validates a candidate
observation, and never writes/builds anything (including the reference
index) - it only reports what already exists and computes
SAFE_TO_RESEARCH from that. If a workflow (a Skill, an agent, a student
prompt) wants to fail closed before researching a country assignment,
it runs this first and stops if SAFE_TO_RESEARCH is false.

It does not change validation, matching, research, writing, or
visualization behavior - none of those scripts import or call this one.
It is an additional, separate gate a workflow chooses to run first.

`reference_data_status` is one of four values:

  - REFERENCE_INDEX_PRESENT      - a local reference index already
    exists AND actually contains at least one row for THIS country
    (checked via pollitik_common.reference_index_contains_country(),
    the same normalize_identifier() rule used everywhere else in this
    project for Country/Series matching); safe regardless of whether
    the master workbook or a snapshot is also present. An index that
    merely exists but was built for a different country/workspace does
    NOT satisfy this - see `reference_index_covers_country` and
    `reference_index_stale_warning` in the report.
  - COUNTRY_SNAPSHOT_BUILDABLE   - the country's tracked reference
    snapshot CSV (see countries/<country>/data/) is present but no
    local index has been built from it yet. NOT safe on its own - the
    snapshot's mere presence is not a substitute for an actually-built
    index (mirrors the same "don't trust an unbuilt/unverified state"
    principle as the empty-staging-file rule below). The calling
    workflow must build the index (python/build_reference_index.py)
    and get a fresh REFERENCE_INDEX_PRESENT result before continuing.
  - MASTER_ONLY_INDEX_BUILDABLE  - no index and no snapshot, but the
    real master workbook is present (e.g. an instructor/production
    workspace). Safe, since a duplicate check against the workbook's
    own data is still possible in principle, but flagged so the
    workflow knows reference_lookup.py needs an index built first.
  - NO_REFERENCE_DATA            - none of the index, a country
    snapshot, or the master workbook is present. Unsafe: there is no
    way at all to check a new candidate against existing data.

Usage:
    python3 python/check_assignment_preflight.py --country Canada
"""

import argparse
import json
import os
import re
import sys

import pollitik_common as pc

# A country AGENTS.md generated by init_country_workspace.py literally
# contains this marker as a section heading or title suffix (see
# init_country_workspace.py's _AGENTS_MD_TEMPLATE: "(SETUP REQUIRED)" in
# the title, "## SETUP REQUIRED — ..." for each unresolved section) until
# a human resolves every SETUP REQUIRED item and rewrites the file with
# real content. Its presence is a genuine, checkable signal that the
# country's assignment scope has not actually been resolved yet - never
# inferred from reference_data_status alone (a country can have a
# buildable snapshot while its AGENTS.md is still an unresolved skeleton,
# e.g. right after someone drops in a reference export before writing the
# real scope). Matched only as a heading/title marker (not a bare
# substring) so a resolved AGENTS.md may still safely describe/quote the
# marker in ordinary prose without re-triggering this check on itself.
SETUP_REQUIRED_MARKER_RE = re.compile(r"^#{1,6}\s*SETUP REQUIRED\b|\(SETUP REQUIRED\)", re.MULTILINE)

# A country AGENTS.md documents its own required Skill/reference-profile
# files as backtick-quoted paths (see e.g. countries/canada/AGENTS.md,
# countries/australia/AGENTS.md). Rather than hardcoding a naming
# convention (which would break for a non-PM office), preflight verifies
# the country's own AGENTS.md claims are actually true: every Skill/
# reference-profile path IT references must actually exist on disk. A
# country AGENTS.md that references nothing (e.g. a minimal test fixture)
# trivially satisfies this - there is nothing to verify - so this never
# regresses a workspace that predates this check.
COUNTRY_SKILL_PATH_RE = re.compile(r"`(\.claude/skills/[^`\s]+?SKILL\.md)`")
COUNTRY_REFERENCE_PROFILE_PATH_RE = re.compile(
    r"`(\.claude/skills/pollitik-executive-support/references/[^`\s]+?\.md)`"
)


def check_country_workspace_readiness(project_dir, country_agents_md_path, country_agents_md_exists):
    """Read-only: inspects the country's own AGENTS.md text (never any
    other file's claims about it) and reports whether the scope/Skill/
    reference-profile setup it documents is genuinely present - not
    merely that the AGENTS.md file exists. Returns a dict always
    containing every key below; never raises (a missing/unreadable file
    fails closed, i.e. reported as not-ready, exactly like every other
    fail-closed check in this script)."""
    result = {
        "agents_md_declares_setup_required": None,
        "declared_skill_paths": [],
        "declared_skill_paths_missing": [],
        "declared_reference_profile_paths": [],
        "declared_reference_profile_paths_missing": [],
        "ready": False,
    }
    if not country_agents_md_exists:
        return result

    try:
        with open(country_agents_md_path, "r", encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return result

    declares_setup_required = bool(SETUP_REQUIRED_MARKER_RE.search(text))
    skill_paths = sorted(set(COUNTRY_SKILL_PATH_RE.findall(text)))
    profile_paths = sorted(set(COUNTRY_REFERENCE_PROFILE_PATH_RE.findall(text)))
    missing_skill_paths = [p for p in skill_paths if not os.path.isfile(os.path.join(project_dir, p))]
    missing_profile_paths = [p for p in profile_paths if not os.path.isfile(os.path.join(project_dir, p))]

    result.update({
        "agents_md_declares_setup_required": declares_setup_required,
        "declared_skill_paths": skill_paths,
        "declared_skill_paths_missing": missing_skill_paths,
        "declared_reference_profile_paths": profile_paths,
        "declared_reference_profile_paths_missing": missing_profile_paths,
        "ready": (
            not declares_setup_required
            and not missing_skill_paths
            and not missing_profile_paths
        ),
    })
    return result


# Re-exported so every script that does `from check_assignment_preflight
# import normalize_country_slug` gets the one canonical implementation in
# pollitik_common.py, never a reimplementation that could silently
# disagree with it. NOTE: this is the plain (non-alias-aware) slug -
# scripts that need to resolve a student-typed alias (e.g. "UK") to the
# same countries/<slug>/ folder the exporters use must call
# pc.canonical_country_slug()/pc.resolve_country_input() directly, not
# this name (see check() below for the pattern).
normalize_country_slug = pc.normalize_country_slug


def default_country_snapshot_path(project_dir, country_slug):
    return os.path.join(project_dir, "countries", country_slug, "data",
                         "{}_reference_snapshot.csv".format(country_slug))


def check(country, project_dir=None, index_path=None, workbook_path=None,
          staging_file=None, allowed_domains_path=None, country_snapshot_path=None):
    """Pure inspection: every path below is checked with os.path.exists
    (or pc.read_allowed_domains, itself a read-only file read) only.
    Nothing is created, built, fetched, staged, or written."""
    project_dir = project_dir or pc.PROJECT_DIR
    index_path = index_path or pc.REFERENCE_INDEX_PATH
    workbook_path = workbook_path or pc.DEFAULT_MASTER_WORKBOOK
    staging_file = staging_file or pc.STAGING_FILE
    allowed_domains_path = allowed_domains_path or pc.ALLOWED_DOMAINS_PATH

    # Resolve aliases (e.g. "UK" -> "United Kingdom") through the one
    # centralized resolver in pollitik_common.py before deriving the
    # folder slug or matching against the reference index - never
    # reimplemented here. A deliberately-ambiguous input (bare "France")
    # fails closed like every other check in this script, rather than
    # raising, per this function's own "never raises" contract.
    try:
        resolved_country = pc.resolve_country_input(country)
        country_slug = pc.canonical_country_slug(country)
    except pc.AmbiguousCountryError as exc:
        return {
            "country": country,
            "resolved_country": None,
            "country_slug": None,
            "repo_root_found": os.path.isdir(project_dir),
            "repo_root": project_dir,
            "root_agents_md_exists": None,
            "root_agents_md_path": None,
            "country_agents_md_exists": None,
            "country_agents_md_path": None,
            "country_workspace_readiness": None,
            "allowed_domains_path": allowed_domains_path,
            "allowed_domains_exists": None,
            "allowed_domains_usable_count": None,
            "allowed_domains_ok": None,
            "reference_index_path": index_path,
            "reference_index_exists": None,
            "reference_index_covers_country": None,
            "reference_index_stale_warning": None,
            "master_workbook_path": workbook_path,
            "master_workbook_exists": None,
            "country_snapshot_path": None,
            "country_snapshot_exists": None,
            "suggested_index_build_command": None,
            "staging_file_path": staging_file,
            "staging_file_exists": None,
            "staging_file_note": None,
            "reference_data_status": "AMBIGUOUS_COUNTRY",
            "reference_data_note": str(exc),
            "unsafe_reasons": [str(exc)],
            "reason": str(exc),
            "SAFE_TO_RESEARCH": False,
            "instruction": (
                "SAFE_TO_RESEARCH=false. STOP - '{}' is ambiguous. Resolve "
                "it to a specific Master Country value before doing "
                "anything else.".format(country)
            ),
        }

    root_agents_md_path = os.path.join(project_dir, "AGENTS.md")
    country_agents_md_path = os.path.join(project_dir, "countries", country_slug, "AGENTS.md")
    country_snapshot_path = country_snapshot_path or default_country_snapshot_path(project_dir, country_slug)

    repo_root_found = os.path.isdir(project_dir)
    root_agents_md_exists = os.path.isfile(root_agents_md_path)
    country_agents_md_exists = os.path.isfile(country_agents_md_path)

    allowed_domains_exists = os.path.isfile(allowed_domains_path)
    # Same skip-blank/skip-"#"-comment rule as pc.read_allowed_domains(),
    # applied directly to whatever path was resolved above (the module-level
    # pc.read_allowed_domains() always reads pc.ALLOWED_DOMAINS_PATH, which
    # is not necessarily this path when --allowed-domains overrides it).
    usable_domains = []
    if allowed_domains_exists:
        with open(allowed_domains_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    usable_domains.append(line.lower())
    allowed_domains_usable_count = len(usable_domains)
    allowed_domains_ok = allowed_domains_exists and allowed_domains_usable_count > 0

    reference_index_exists = os.path.isfile(index_path)
    master_workbook_exists = os.path.isfile(workbook_path)
    country_snapshot_exists = os.path.isfile(country_snapshot_path)
    staging_file_exists = os.path.isfile(staging_file)

    # An index can EXIST but have been built for a different country or
    # an unrelated workspace (e.g. a leftover whole-master index from a
    # prior session, or another country's snapshot-built index sitting
    # in a shared local data/ dir). Existence alone was previously
    # treated as sufficient - this check closes that gap: only an index
    # that actually contains at least one row whose Country normalizes
    # to this country is trusted as reference data for it. Read-only,
    # never raises (pc.reference_index_contains_country fails closed on
    # a missing/corrupt index), and never affects any other exists/*
    # field above.
    reference_index_covers_country = None
    reference_index_stale_warning = None
    if reference_index_exists:
        country_norm = pc.normalize_identifier(resolved_country)
        reference_index_covers_country = pc.reference_index_contains_country(index_path, country_norm)
        if not reference_index_covers_country:
            reference_index_stale_warning = (
                "A local reference index exists at '{}' but no row in it has a "
                "Country value that normalizes to '{}' - it was likely built for "
                "a different country or an unrelated workspace. It is NOT being "
                "treated as reference data for {}; rebuild it from {}'s own "
                "tracked snapshot (or the master workbook) before "
                "researching.".format(index_path, country_norm, resolved_country, resolved_country)
            )

    country_workspace_readiness = check_country_workspace_readiness(
        project_dir, country_agents_md_path, country_agents_md_exists
    )

    reasons = []
    if not repo_root_found:
        reasons.append(
            "Repo root '{}' does not exist or is not a directory.".format(project_dir)
        )
    if not root_agents_md_exists:
        reasons.append(
            "Root AGENTS.md ('{}') is missing; repository-wide ground rules "
            "are unavailable.".format(root_agents_md_path)
        )
    if not country_agents_md_exists:
        reasons.append(
            "countries/{}/AGENTS.md ('{}') is missing; country-specific rules "
            "are unavailable.".format(country_slug, country_agents_md_path)
        )
    if not allowed_domains_ok:
        if not allowed_domains_exists:
            reasons.append(
                "Approved-domain list ('{}') is missing; no source domain can "
                "be verified as approved.".format(allowed_domains_path)
            )
        else:
            reasons.append(
                "Approved-domain list ('{}') exists but contains no usable "
                "(non-comment, non-blank) domains.".format(allowed_domains_path)
            )
    # Country-workspace readiness: the country's own AGENTS.md is the
    # single source of truth here, never inferred from reference_data_status
    # alone - a country can have a perfectly buildable snapshot while its
    # AGENTS.md is still an unresolved SETUP REQUIRED skeleton (e.g. right
    # after a reference export lands before the real scope/Skill/profile
    # do). Only evaluated when the country AGENTS.md exists at all - its
    # absence is already reported above and must not be double-counted.
    if country_agents_md_exists and country_workspace_readiness["agents_md_declares_setup_required"]:
        reasons.append(
            "countries/{}/AGENTS.md still contains an unresolved 'SETUP "
            "REQUIRED' marker; the assignment scope has not actually been "
            "confirmed yet.".format(country_slug)
        )
    if country_agents_md_exists and country_workspace_readiness["declared_skill_paths_missing"]:
        reasons.append(
            "countries/{}/AGENTS.md references a country Skill file that "
            "does not exist on disk: {}.".format(
                country_slug, ", ".join(country_workspace_readiness["declared_skill_paths_missing"])
            )
        )
    if country_agents_md_exists and country_workspace_readiness["declared_reference_profile_paths_missing"]:
        reasons.append(
            "countries/{}/AGENTS.md references a reference profile file that "
            "does not exist on disk: {}.".format(
                country_slug,
                ", ".join(country_workspace_readiness["declared_reference_profile_paths_missing"]),
            )
        )
    # Priority: an already-built index beats everything else; a tracked
    # country snapshot (small, student-safe, needs no master workbook) is
    # preferred over the master-workbook-only path when both could apply,
    # since building from the snapshot is the intended student path.
    # Order matters here and must match the reasons/instruction text below.
    suggested_index_build_command = None
    if reference_index_exists and reference_index_covers_country:
        reference_data_status = "REFERENCE_INDEX_PRESENT"
        reference_data_note = (
            "The DuckDB reference index is present and contains at least "
            "one row for this country, so it can be used via "
            "python/reference_lookup.py for duplicate/reference checks. "
            "This is sufficient even if the master workbook itself is not "
            "present in this workspace."
        )
    elif country_snapshot_exists:
        reference_data_status = "COUNTRY_SNAPSHOT_BUILDABLE"
        suggested_index_build_command = (
            "python python/build_reference_index.py --workbook {} --index {}"
            .format(country_snapshot_path, index_path)
        )
        reference_data_note = (
            "A tracked country reference snapshot is present ('{}') but no "
            "local reference index covering this country has been built "
            "from it yet. Its mere presence is NOT sufficient - build the "
            "index first ('{}'), then re-run this preflight check and "
            "confirm it reports REFERENCE_INDEX_PRESENT before researching. "
            "This never requires the real master workbook.".format(
                country_snapshot_path, suggested_index_build_command)
        )
        reasons.append(
            "A country reference snapshot is present ('{}') but a local "
            "reference index covering this country has not been built "
            "from it yet. Build it first ('{}') and re-run preflight - do "
            "not start research until SAFE_TO_RESEARCH is true.".format(
                country_snapshot_path, suggested_index_build_command)
        )
        if reference_index_stale_warning:
            reasons.append(reference_index_stale_warning)
    elif master_workbook_exists:
        reference_data_status = "MASTER_ONLY_INDEX_BUILDABLE"
        reference_data_note = (
            "No reference index covering this country was found, but the "
            "master workbook is present. python/reference_lookup.py reads "
            "only the index and will silently report found_index=false / "
            "zero rows without one - that is NOT evidence that no "
            "duplicates exist. Build a fresh index once via 'python "
            "python/build_reference_index.py' before relying on "
            "reference_lookup.py for duplicate/reference checks. That is a "
            "first-time build, not the routine rebuild "
            "countries/<country>/AGENTS.md says to avoid - this preflight "
            "check does not build it itself."
        )
        if reference_index_stale_warning:
            # This branch is otherwise SAFE_TO_RESEARCH=true (the master
            # workbook itself is authoritative) - the stale index is
            # surfaced for transparency in reference_data_note/the
            # dedicated field below, but deliberately NOT appended to
            # `reasons`, since doing so would incorrectly flip an
            # otherwise-safe instructor/production workspace to unsafe.
            reference_data_note += " " + reference_index_stale_warning
    else:
        reference_data_status = "NO_REFERENCE_DATA"
        reference_data_note = (
            "Neither a reference index covering this country, a country "
            "reference snapshot, nor the master workbook is present in "
            "this workspace."
        )
        reasons.append(
            "Neither a reference index covering this country ('{}'), a "
            "country reference snapshot ('{}'), nor the master workbook "
            "('{}') is present; there is no way to check new candidates "
            "against existing/duplicate records before researching."
            .format(index_path, country_snapshot_path, workbook_path)
        )
        if reference_index_stale_warning:
            reasons.append(reference_index_stale_warning)

    safe_to_research = len(reasons) == 0

    if safe_to_research:
        instruction = (
            "SAFE_TO_RESEARCH=true. Proceed: inspect the existing "
            "assignment/reference state (the country reference profile and "
            "python/reference_lookup.py against the existing index), then "
            "research only approved domains from config/allowed_domains.txt."
        )
    elif reference_data_status == "COUNTRY_SNAPSHOT_BUILDABLE":
        instruction = (
            "SAFE_TO_RESEARCH=false. STOP before any web research or "
            "staging. Build the local reference index first: run `{}`, "
            "then re-run this preflight check.".format(suggested_index_build_command)
        )
    else:
        instruction = (
            "SAFE_TO_RESEARCH=false. STOP before any web research or "
            "staging. Resolve every item in 'unsafe_reasons' first."
        )

    return {
        "country": country,
        "resolved_country": resolved_country,
        "country_slug": country_slug,
        "repo_root_found": repo_root_found,
        "repo_root": project_dir,
        "root_agents_md_exists": root_agents_md_exists,
        "root_agents_md_path": root_agents_md_path,
        "country_agents_md_exists": country_agents_md_exists,
        "country_agents_md_path": country_agents_md_path,
        "country_workspace_readiness": country_workspace_readiness,
        "allowed_domains_path": allowed_domains_path,
        "allowed_domains_exists": allowed_domains_exists,
        "allowed_domains_usable_count": allowed_domains_usable_count,
        "allowed_domains_ok": allowed_domains_ok,
        "reference_index_path": index_path,
        "reference_index_exists": reference_index_exists,
        "reference_index_covers_country": reference_index_covers_country,
        "reference_index_stale_warning": reference_index_stale_warning,
        "master_workbook_path": workbook_path,
        "master_workbook_exists": master_workbook_exists,
        "country_snapshot_path": country_snapshot_path,
        "country_snapshot_exists": country_snapshot_exists,
        "suggested_index_build_command": suggested_index_build_command,
        "staging_file_path": staging_file,
        "staging_file_exists": staging_file_exists,
        "staging_file_note": (
            "Informational only - an empty or newly created (or entirely "
            "absent) staging file is never evidence that an observation is "
            "new. It does not affect SAFE_TO_RESEARCH either way; "
            "duplicate-checking must use the reference index / master "
            "workbook, not staging-file presence or absence."
        ),
        "reference_data_status": reference_data_status,
        "reference_data_note": reference_data_note,
        "unsafe_reasons": reasons,
        "reason": "; ".join(reasons) if reasons else None,
        "SAFE_TO_RESEARCH": safe_to_research,
        "instruction": instruction,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--country", required=True, help="e.g. Canada")
    parser.add_argument("--index", default=None, help="Override reference_index.duckdb path (testing only).")
    parser.add_argument("--workbook", default=None, help="Override master workbook path (testing only).")
    parser.add_argument("--staging-file", default=None, help="Override staging file path (testing only).")
    parser.add_argument("--allowed-domains", default=None, help="Override allowed_domains.txt path (testing only).")
    parser.add_argument("--country-snapshot", default=None, help="Override the country reference-snapshot CSV path (testing only).")
    args = parser.parse_args()

    result = check(
        args.country,
        index_path=args.index,
        workbook_path=args.workbook,
        staging_file=args.staging_file,
        allowed_domains_path=args.allowed_domains,
        country_snapshot_path=args.country_snapshot,
    )

    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result["SAFE_TO_RESEARCH"] else 1)


if __name__ == "__main__":
    main()
